# Get package location hint from environment variable (if any)
if(NOT sentry_ROOT_DIR AND DEFINED ENV{sentry_ROOT_DIR})
  set(sentry_ROOT_DIR "$ENV{sentry_ROOT_DIR}" CACHE PATH
      "sentry base directory location (optional, used for nonstandard installation paths)")
endif()

# Search path for nonstandard package locations
if(sentry_ROOT_DIR)
  set(sentry_INCLUDE_PATH PATHS "${sentry_ROOT_DIR}/include" NO_DEFAULT_PATH)
  set(sentry_LIBRARY_PATH PATHS "${sentry_ROOT_DIR}/lib"     NO_DEFAULT_PATH)
else()
  set(sentry_INCLUDE_PATH "")
  set(lz4_LIBRARY_PATH "")
endif()

# Find headers and libraries
find_path(sentry_INCLUDE_DIR NAMES sentry.h PATH_SUFFIXES "sentry" ${sentry_INCLUDE_PATH})
find_library(sentry_LIBRARY  NAMES sentry   PATH_SUFFIXES "sentry" ${sentry_LIBRARY_PATH})

# extract sdk version
if (sentry_INCLUDE_DIR)
  file(STRINGS "${sentry_INCLUDE_DIR}/sentry.h" version-file
    REGEX "#define[ \t]+SENTRY_SDK_VERSION .*")
  list(GET version-file 0 version_line)
  string(REGEX REPLACE "^#define[ \t]+SENTRY_SDK_VERSION[ \t]+\"([0-9]+\.[0-9]+\.[0-9]+)\"" "\\1" sentry_VERSION ${version_line})
endif()

mark_as_advanced(sentry_INCLUDE_DIR sentry_LIBRARY)

# Output variables generation
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(sentry REQUIRED_VARS sentry_LIBRARY sentry_INCLUDE_DIR
  VERSION_VAR sentry_VERSION)

set(sentry_FOUND ${SENTRY_FOUND}) # Enforce case-correctness: Set appropriately cased variable...
unset(SENTRY_FOUND) # ...and unset uppercase variable generated by find_package_handle_standard_args

if(sentry_FOUND)
  set(sentry_INCLUDE_DIRS ${sentry_INCLUDE_DIR})
  set(sentry_LIBRARIES ${sentry_LIBRARY})

  if(NOT TARGET sentry::sentry)
    add_library(sentry::sentry UNKNOWN IMPORTED)
    set_property(TARGET sentry::sentry PROPERTY IMPORTED_LOCATION ${sentry_LIBRARY})
    set_property(TARGET sentry::sentry PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${sentry_INCLUDE_DIR})
  endif()
  list(APPEND sentry_TARGETS sentry::sentry)
elseif(sentry_FIND_REQUIRED)
  message(FATAL_ERROR "Unable to find sentry")
endif()
