# Output variables generation

set(OTEL_LIBS 
"opentelemetry-cpp::api"
"opentelemetry-cpp::ext"
"opentelemetry-cpp::sdk"
"opentelemetry-cpp::common"
"opentelemetry-cpp::version"
"opentelemetry-cpp::metrics"
"opentelemetry-cpp::trace"
"opentelemetry-cpp::in_memory_span_exporter"
"opentelemetry-cpp::logs"
"opentelemetry-cpp::otlp_recordable"
"opentelemetry-cpp::otlp_grpc_client"
"opentelemetry-cpp::otlp_grpc_log_record_exporter"
"opentelemetry-cpp::otlp_grpc_exporter"
"opentelemetry-cpp::otlp_http_client"
"opentelemetry-cpp::otlp_grpc_metrics_exporter"
"opentelemetry-cpp::otlp_http_log_record_exporter"
"opentelemetry-cpp::otlp_http_exporter"
"opentelemetry-cpp::otlp_file_client"
"opentelemetry-cpp::otlp_http_metric_exporter"
"opentelemetry-cpp::otlp_file_log_record_exporter"
"opentelemetry-cpp::otlp_file_exporter"
"opentelemetry-cpp::ostream_log_record_exporter"
"opentelemetry-cpp::otlp_file_metric_exporter"
"opentelemetry-cpp::ostream_span_exporter"
"opentelemetry-cpp::ostream_metrics_exporter"
"opentelemetry-cpp::etw_exporter"
"opentelemetry-cpp::elasticsearch_log_record_exporter"
"opentelemetry-cpp::opentracing_shim"
"opentelemetry-cpp::http_client_curl"
)

find_path(opentelemetry_cpp_INCLUDE_DIR NAMES opentelemetry/version.h)
# extract sdk version
if (opentelemetry_cpp_INCLUDE_DIR)
  file(STRINGS "${opentelemetry_cpp_INCLUDE_DIR}/version.h" version-file
    REGEX "#define[ \t]+OPENTELEMETRY_VERSION.*")
  list(GET version-file 0 version_line)
  string(REGEX REPLACE "^#define[ \t]+OPENTELEMETRY_VERSION[ \t]+\"v([0-9]+\.[0-9]+\.[0-9]+)\"" "\\1" opentelemetry_cpp_VERSION ${version_line})
endif()

mark_as_advanced(opentelemetry_cpp_INCLUDE_DIR opentelemetry_cpp_LIBRARY)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(opentelemetry-cpp REQUIRED_VARS opentelemetry_cpp_LIBRARY opentelemetry_cpp_INCLUDE_DIR VERSION_VAR opentelemetry_cpp_VERSION)

set(opentelemetry_cpp_FOUND ${OPENTELEMETRY_CPP_FOUND}) # Enforce case-correctness: Set appropriately cased variable...
unset(OPENTELEMETRY_CPP_FOUND) # ...and unset uppercase variable generated by find_package_handle_standard_args

if(opentelemetry_cpp_FOUND)
  set(opentelemetry_cpp_INCLUDE_DIRS ${opentelemetry_cpp_INCLUDE_DIR})
  set(opentelemetry_cpp_LIBRARIES ${opentelemetry_cpp_LIBRARY})

  message(STATUS "Opentelemetry-cpp found: ${opentelemetry_cpp_LIBRARIES}")
  message(STATUS "Opentelemetry-cpp include: ${opentelemetry_cpp_INCLUDE_DIRS}")

  foreach(OTLIB ${OTEL_LIBS})
    if(NOT TARGET ${OTLIB})
      add_library(${OTLIB} UNKNOWN IMPORTED)
      set_property(TARGET ${OTLIB} PROPERTY IMPORTED_LOCATION ${opentelemetry_cpp_LIBRARY})
      set_property(TARGET ${OTLIB} PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${opentelemetry_cpp_INCLUDE_DIR})
      list(APPEND opentelemetry_cpp_TARGETS  ${OTLIB})
    endif()
  endforeach()

elseif(opentelemetry_cpp_FIND_REQUIRED)
  message(FATAL_ERROR "Unable to find opentelemetry-cpp")
endif()